name:                emqx-auth
version:             0.1.0.0
github:              "Lupino/emqx-auth"
license:             BSD3
author:              "Lupino"
maintainer:          "lmjubuntu@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lupino/emqx-auth#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - yuntan-base
  - wreq
  - yuntan-common-wreq
  - yuntan-common-result
  - hslogger
  - aeson
  - scotty
  - transformers
  - http-types
  - optparse-applicative
  - yaml
  - streaming-commons
  - warp
  - data-default-class

executables:
  emqx-auth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emqx-auth

tests:
  emqx-auth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emqx-auth
